#docker-compose -f docker-compose.yaml up --force-recreate --build -d
version: '3'
services:
  lfg-web:
    restart: always
    container_name: lfg_web
    build:
      dockerfile: ./Dockerfile-web
      context: .
    environment:
      VIRTUAL_HOST: lfg4.staging.glenmurphy.com
      LETSENCRYPT_HOST: lfg4.staging.glenmurphy.com

  lfg-tracker:
    restart: always
    container_name: lfg_tracker
    build:
      dockerfile: ./Dockerfile-tracker
      context: .
    #ports:
    #  - "8000:8000"
    environment:
      VIRTUAL_HOST: ws.lfg4.staging.glenmurphy.com
      VIRTUAL_PORT: 443
      LETSENCRYPT_HOST: ws.lfg4.staging.glenmurphy.com
      LETSENCRYPT_EMAIL: glen@glenmurphy.com
      WEBSOCKETS: 1

networks:
  default:
    external:
      name: nginx-proxy